### ISSUE TITLE
Función randit

### ISSUE THREAD

**Issue by luisperezcantarero** [iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-Albert0PB#1]
La función randint se importa incorrectamente. Debe ser from random import randint en lugar de from random import rand int.

**Comment by Albert0PB** [comment]
¡Recontracórcholis! Debo prestar más atención al importar librerías. Lo soluciono de inmediato.

**Comment by Albert0PB** [comment]
Resuelto. ¡A Dios pongo por testigo que nunca más volveré a importar incorrectamente en Python!

**Comment by luisperezcantarero** [comment]
¡Qué maravillosa transformación! Me alegra profundamente que hayas aprendido esta valiosa lección.
